#! /usr/bin/env ruby
# This console script adapted from:rake
#   http://barkingiguana.com/blog/2009/01/25/scriptconsole-for-your-application/
 
libs = %w{irb/completion app}
 
command_line = []
command_line << "irb"
command_line << libs.inject("") { |acc, lib| acc + %( -r "#{lib}") }
command_line << "--simple-prompt"
command = command_line.join(" ")
 
puts "Welcome to the sinatra-mvc console interface."
exec command
